spring:
  application:
    name: r2dbc-test
  r2dbc:
    username: local
    password: local
    url: r2dbc:postgresql://localhost:8082/test-webflux
  flyway:
    url: jdbc:postgresql://localhost:8082/test-webflux
    locations: classpath:db/postgres/migration
    user: local
    password: local
  main:
    allow-bean-definition-overriding: true

#    Documentação
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    doc-expansion: none
    operations-sorter: alpha
    filter: true

# Loges do banco e consultas
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG